### ISSUE TITLE
Feature: anywidget component (for Python dataframes)

### ISSUE THREAD

**Issue by declann** [rpbouman/huey#145]
This is something that could follow after #143

[Quak](https://github.com/manzt/quak) is an example of a DuckDB component that is getting a bit of attention in the Python community right now. (its header UI is also super interesting!)

It's very easy to integrate Quak into Jupyter notebooks to interact/explore things about a dataset (any dataframe-like object).

Huey can also be interesting in this usecase I think. With #143 I think it's a matter of developing an [anywidget](https://github.com/manzt/anywidget) wrapper: in many ways probably quite similar to Quak (which is MIT licensed).

**Comment by rpbouman** [comment]
I looked into this for a bit, and my view is that is probably best dealt with in a separate project.
I do not have enough experience with Jupyter notebooks to have a clear enough vision on what this development would take.

If someone picks this up then I would be open to make any changes on the huey side that they would need to enable and/or facilitate them.
