### ISSUE TITLE
Disabling all filter items causes an error

### ISSUE THREAD

**Issue by IvoMoor** [rpbouman/huey#255]
When disabling all items for a filter, an error occurs:
![image](https://github.com/user-attachments/assets/55e7554e-020d-47f5-a504-c7d6bb7b3fcb)

Error shown:
![image](https://github.com/user-attachments/assets/576d4a55-8631-4001-bccf-ca4168d8b6a4)

**Comment by rpbouman** [comment]
I can't reproduce it. Here's my query:

![image](https://github.com/user-attachments/assets/e057d2a4-edfd-48ab-9a82-ae449fa1d267)

Please pull and try again. If you have the same issue still, please try to share a dataset and query that demonstrates the problem.
