### ISSUE TITLE
Icons: change icons for min and max.

### ISSUE THREAD

**Issue by rpbouman** [rpbouman/huey#52]
The min and max icons are a constant source of distraction when doing demos and it's now way beyond level chuckle.

![image](https://github.com/rpbouman/huey/assets/647315/53568700-8934-40de-8476-68c0f29aaa2e)

**Comment by JDavidson00** [comment]
Hi Roland,

I am interested in fixing this issue. Could you assign it to me?

Thanks,
Josh Davidson

**Comment by rpbouman** [comment]
@JDavidson00 sure, just did! Thanks for helping out.

That said, if at all possible I would really like to stick to using the Tabler project icons. I have created an issue there too: https://github.com/tabler/tabler-icons/issues/992

Ideally, they would understand the issue and come up with a new design and we would then just wait for that to find it's course.
A slightly less ideal solution would be to find good-enough alternatives in the Tabler icon set.
If those two are not possible then I think some reconsideration is needed. Agree?

**Comment by rpbouman** [comment]
Fixed now. Thanks @JDavidson00 for suggesting the alternatives, I like it much better now!
