### ISSUE TITLE
error in column sum

### ISSUE THREAD

**Issue by eugeniosinan** [rpbouman/huey#78]
When using a duckdb file in which one of the columns is numeric, the following error appears. I've done several tests with other banks and they all show the same error.
Note: With csv files it gave the same error.

![image](https://github.com/rpbouman/huey/assets/71833563/e7033adf-2c50-4578-b8d8-3551956adc4e)

**Comment by rpbouman** [comment]
Hi! Thank you for your interest in Huey and thanks for filing the issue. 

I'd love to help! Can you send me a few things:
- are you running the online Huey demo (https://rpbouman.github.io/huey/src/index.html) or a local clone of the repository?
- If it's a local clone of the repository, can you then please check if you can reproduce it on the develop branch after pulling the latest changes?
- a sample file that illustrates the behavior
- a screenshot of the "Locale" tab in your "settings" Dialog (see ad 1)
- a screenshot of the Huey about dialog so we can see the version number (see ad 2)

ad 1:
You can open the settings dialog by clicking the Gear button located on the right side of the top toolbar:
![image](https://github.com/rpbouman/huey/assets/647315/fbbb7825-ad83-4dbb-a7fe-1cd0fadea3ef)

ad 2: 
You can open the about dialog by clicking the Info button located on the right side of the top toolbar:
![image](https://github.com/rpbouman/huey/assets/647315/a3cc3588-6cda-476e-b910-fb65fbb11119)


Thanks in advance

**Comment by eugeniosinan** [comment]
Thank you in advance for the response.
I tested this link and got the same error.
[db_vacinas_23_bckp.csv](https://github.com/rpbouman/huey/files/14983737/db_vacinas_23_bckp.csv)
![image](https://github.com/rpbouman/huey/assets/71833563/78a452dd-e697-48e1-9452-c969d1aca1a6)
![image](https://github.com/rpbouman/huey/assets/71833563/6a648b6a-911f-4cae-954f-61eecbd87a2f)
![image](https://github.com/rpbouman/huey/assets/71833563/0d25ac74-d68d-44e6-a944-9aea3b6f082d)

Using Chrome as a browser.

**Comment by rpbouman** [comment]
This is now fixed. Thanks for helping making Huey better! 

![image](https://github.com/rpbouman/huey/assets/647315/72861c6e-b40a-4783-b620-dd217b78ccab)

**Comment by eugeniosinan** [comment]
Thank you very much for such a quick correction!
Congratulations on the excellent work!
