### ISSUE TITLE
Feature: Hide repetitive values in both columns and rows

### ISSUE THREAD

**Issue by IvoMoor** [rpbouman/huey#80]
A setting to hide repetitive column and row values would be nice for a better readability of the results. 

With the setting switched off, the results should be displayed like:
col1 | col2
--- | ---
Value A | X
Value A | Y
Value A | Z
Value B | X
Value B | Y
Value B | Z

When switched on, it should look like:
col1 | col2
--- | ---
Value A | X
| | Y
| | Z
Value B | X
| | Y
| | Z

**Comment by rpbouman** [comment]
![image](https://github.com/user-attachments/assets/733a8f3d-1559-472b-a48a-1f0277fbe8b4)

**Comment by rpbouman** [comment]
![image](https://github.com/user-attachments/assets/89ab6caf-2250-4cfa-9eef-9accd9d55912)
