### ISSUE TITLE
Feature: Ability to save a report

### ISSUE THREAD

**Issue by IvoMoor** [rpbouman/huey#81]
It would be nice if a current state of a pivot table could be stored (and shared). The current state should include the dimensions and measures on each of the axis and the filters.

**Comment by rpbouman** [comment]
Rudimentary support is now available as the url hash gets updated everytime a query is successfully rendered.
Saving the query is done simply by bookmarking it.

**Comment by declann** [comment]
> Rudimentary support is now available as the url hash gets updated everytime a query is successfully rendered. Saving the query is done simply by bookmarking it.

I like this solution a lot to save and share reports.

Now after #144 I thought I could try sharing a report as a URL, but found this doesn't work

https://rpbouman.github.io/huey/src/index.html#JTdCJTIycXVlcnlNb2RlbCUyMiUzQSU3QiUyMmRhdGFzb3VyY2VJZCUyMiUzQSUyMmZpbGUlM0ElNUMlMjJodHRwcyUzQSUyRiUyRmR1Y2tkYi5vcmclMkZkYXRhJTJGaG9sZGluZ3MucGFycXVldCU1QyUyMiUyMiUyQyUyMmNlbGxzSGVhZGVycyUyMiUzQSUyMmNvbHVtbnMlMjIlMkMlMjJheGVzJTIyJTNBJTdCJTIyY2VsbHMlMjIlM0ElNUIlN0IlMjJjb2x1bW4lMjIlM0ElMjJzaGFyZXMlMjIlMkMlMjJjb2x1bW5UeXBlJTIyJTNBJTIyRE9VQkxFJTIyJTJDJTIyZGVyaXZhdGlvbiUyMiUzQW51bGwlMkMlMjJhZ2dyZWdhdG9yJTIyJTNBJTIyc3VtJTIyJTdEJTVEJTJDJTIycm93cyUyMiUzQSU1QiU3QiUyMmNvbHVtbiUyMiUzQSUyMndoZW4lMjIlMkMlMjJjb2x1bW5UeXBlJTIyJTNBJTIyVElNRVNUQU1QJTIyJTJDJTIyZGVyaXZhdGlvbiUyMiUzQSUyMnllYXIlMjIlMkMlMjJhZ2dyZWdhdG9yJTIyJTNBbnVsbCU3RCU1RCU3RCU3RCU3RA==

![image](https://github.com/user-attachments/assets/0e08cb4d-bb0e-4ab3-9d21-c6dc4bd83500)
