### ISSUE TITLE
TransactionContext Error: Failed to commit: File is not opened in write mode.

### ISSUE THREAD

**Issue by dash-awake** [rpbouman/huey#86]
I am trying to load a large duckdb file (700MB), and the UI errors out with the following message "TransactionContext Error: Failed to commit: File is not opened in write mode.".

The file is writable on the file system. I am using a Mac, and I start the UI after cloning the repo. Is there a workaround for this?
<img width="1212" alt="Screenshot 2024-05-22 at 9 18 35 AM" src="https://github.com/rpbouman/huey/assets/35353302/85c568a1-c854-47cb-bed1-b30b082daca7">

**Comment by rpbouman** [comment]
Hi! Thanks for your interest in Huey.

What kind of file is it? Would it be possible to share it? If not, could you try to cut the file in half and try to load that? 

For testing I often use the large volume taxi trip data dataset (https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page).
Those are 450 MB Parquet files, and I can open multiple of those at once without issue.

If curring in half does work then I suspect it is an issue with duckdb wasm. The workaround in that case would be to indeed cut the files in half. When loading in Huey, Huey will detect whether files have the same column layout (names + datatypes), and offer you to analyze either the individual files, or a union of all those files, effectively allowing you to analyze the entire dataset.

**Comment by rpbouman** [comment]
Haven't heard back, closing.
