### ISSUE TITLE
Missing label for NULL filter value 

### ISSUE THREAD

**Issue by IvoMoor** [rpbouman/huey#91]
![image](https://github.com/rpbouman/huey/assets/9193059/5a3cd483-5582-4a5b-aec5-699c0f2a5c37)

![image](https://github.com/rpbouman/huey/assets/9193059/60759235-4a97-4aa8-bffe-d4be46fe6d10)

**Comment by rpbouman** [comment]
There should be a general setting that allows the user to configure a string to represent how NULL values should be displayed.
Probably , this setting should be consistent - same for grid, axes, query ui, and filter.
