### ISSUE TITLE
Handle axis labels for totals

### ISSUE THREAD

**Issue by IvoMoor** [rpbouman/huey#98]
![image](https://github.com/user-attachments/assets/f8fb8319-30aa-4078-88ee-487fe80e9a48)

**Comment by rpbouman** [comment]
Still wrong for this case:

![image](https://github.com/user-attachments/assets/0eac4a50-f04e-4e3e-961b-7cbaa71298cd)

JTdCJTIydmlld0NsYXNzJTIyJTNBJTIyUGl2b3RUYWJsZVVpJTIyJTJDJTIycXVlcnlNb2RlbCUyMiUzQSU3QiUyMmRhdGFzb3VyY2VJZCUyMiUzQSUyMmZpbGUlM0ElNUMlMjJmaHZodl90cmlwZGF0YV8yMDIzLTAxLnBhcnF1ZXQlNUMlMjIlMjIlMkMlMjJjZWxsc0hlYWRlcnMlMjIlM0ElMjJjb2x1bW5zJTIyJTJDJTIyYXhlcyUyMiUzQSU3QiUyMmNlbGxzJTIyJTNBJTVCJTdCJTIyY29sdW1uJTIyJTNBJTIyKiUyMiUyQyUyMmNvbHVtblR5cGUlMjIlM0ElMjJJTlRFR0VSJTIyJTJDJTIyZGVyaXZhdGlvbiUyMiUzQW51bGwlMkMlMjJhZ2dyZWdhdG9yJTIyJTNBJTIyY291bnQlMjIlN0QlNUQlMkMlMjJjb2x1bW5zJTIyJTNBJTVCJTdCJTIyY29sdW1uJTIyJTNBJTIyZGlzcGF0Y2hpbmdfYmFzZV9udW0lMjIlMkMlMjJjb2x1bW5UeXBlJTIyJTNBJTIyVkFSQ0hBUiUyMiUyQyUyMmRlcml2YXRpb24lMjIlM0FudWxsJTJDJTIyYWdncmVnYXRvciUyMiUzQW51bGwlN0QlMkMlN0IlMjJjb2x1bW4lMjIlM0ElMjJodmZoc19saWNlbnNlX251bSUyMiUyQyUyMmNvbHVtblR5cGUlMjIlM0ElMjJWQVJDSEFSJTIyJTJDJTIyZGVyaXZhdGlvbiUyMiUzQW51bGwlMkMlMjJhZ2dyZWdhdG9yJTIyJTNBbnVsbCUyQyUyMmluY2x1ZGVUb3RhbHMlMjIlM0F0cnVlJTdEJTVEJTJDJTIyZmlsdGVycyUyMiUzQSU1QiU3QiUyMmNvbHVtbiUyMiUzQSUyMmRpc3BhdGNoaW5nX2Jhc2VfbnVtJTIyJTJDJTIyY29sdW1uVHlwZSUyMiUzQSUyMlZBUkNIQVIlMjIlMkMlMjJkZXJpdmF0aW9uJTIyJTNBbnVsbCUyQyUyMmFnZ3JlZ2F0b3IlMjIlM0FudWxsJTJDJTIyZmlsdGVyJTIyJTNBJTdCJTIyZmlsdGVyVHlwZSUyMiUzQSUyMmluJTIyJTJDJTIydmFsdWVzJTIyJTNBJTdCJTIyQjAyNzY0JTIyJTNBJTdCJTIydmFsdWUlMjIlM0ElMjJCMDI3NjQlMjIlMkMlMjJsYWJlbCUyMiUzQSUyMkIwMjc2NCUyMiUyQyUyMmxpdGVyYWwlMjIlM0ElMjInQjAyNzY0JyUyMiU3RCUyQyUyMkIwMjc2NSUyMiUzQSU3QiUyMnZhbHVlJTIyJTNBJTIyQjAyNzY1JTIyJTJDJTIybGFiZWwlMjIlM0ElMjJCMDI3NjUlMjIlMkMlMjJsaXRlcmFsJTIyJTNBJTIyJ0IwMjc2NSclMjIlN0QlMkMlMjJCMDI4MzUlMjIlM0ElN0IlMjJ2YWx1ZSUyMiUzQSUyMkIwMjgzNSUyMiUyQyUyMmxhYmVsJTIyJTNBJTIyQjAyODM1JTIyJTJDJTIybGl0ZXJhbCUyMiUzQSUyMidCMDI4MzUnJTIyJTdEJTdEJTJDJTIydG9WYWx1ZXMlMjIlM0ElN0IlN0QlMkMlMjJ0b2dnbGVTdGF0ZSUyMiUzQSUyMmNsb3NlZCUyMiU3RCU3RCU1RCUyQyUyMnJvd3MlMjIlM0ElNUIlN0IlMjJjb2x1bW4lMjIlM0ElMjJvcmlnaW5hdGluZ19iYXNlX251bSUyMiUyQyUyMmNvbHVtblR5cGUlMjIlM0ElMjJWQVJDSEFSJTIyJTJDJTIyZGVyaXZhdGlvbiUyMiUzQW51bGwlMkMlMjJhZ2dyZWdhdG9yJTIyJTNBbnVsbCUyQyUyMmluY2x1ZGVUb3RhbHMlMjIlM0F0cnVlJTdEJTVEJTdEJTdEJTdE

**Comment by rpbouman** [comment]
Note that the row axis does not have that issue:

![image](https://github.com/user-attachments/assets/fc31d64f-5fc3-464d-90a3-1e4e22b0441a)

**Comment by rpbouman** [comment]
The rows axis has another issue though:

![image](https://github.com/user-attachments/assets/76900906-b952-4105-b023-72bba717d09c)

JTdCJTIydmlld0NsYXNzJTIyJTNBJTIyUGl2b3RUYWJsZVVpJTIyJTJDJTIycXVlcnlNb2RlbCUyMiUzQSU3QiUyMmRhdGFzb3VyY2VJZCUyMiUzQSUyMmZpbGUlM0ElNUMlMjJmaHZodl90cmlwZGF0YV8yMDIzLTAxLnBhcnF1ZXQlNUMlMjIlMjIlMkMlMjJjZWxsc0hlYWRlcnMlMjIlM0ElMjJjb2x1bW5zJTIyJTJDJTIyYXhlcyUyMiUzQSU3QiUyMmNlbGxzJTIyJTNBJTVCJTdCJTIyY29sdW1uJTIyJTNBJTIyKiUyMiUyQyUyMmNvbHVtblR5cGUlMjIlM0ElMjJJTlRFR0VSJTIyJTJDJTIyZGVyaXZhdGlvbiUyMiUzQW51bGwlMkMlMjJhZ2dyZWdhdG9yJTIyJTNBJTIyY291bnQlMjIlN0QlNUQlMkMlMjJjb2x1bW5zJTIyJTNBJTVCJTdCJTIyY29sdW1uJTIyJTNBJTIyb3JpZ2luYXRpbmdfYmFzZV9udW0lMjIlMkMlMjJjb2x1bW5UeXBlJTIyJTNBJTIyVkFSQ0hBUiUyMiUyQyUyMmRlcml2YXRpb24lMjIlM0FudWxsJTJDJTIyYWdncmVnYXRvciUyMiUzQW51bGwlMkMlMjJpbmNsdWRlVG90YWxzJTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMmZpbHRlcnMlMjIlM0ElNUIlN0IlMjJjb2x1bW4lMjIlM0ElMjJkaXNwYXRjaGluZ19iYXNlX251bSUyMiUyQyUyMmNvbHVtblR5cGUlMjIlM0ElMjJWQVJDSEFSJTIyJTJDJTIyZGVyaXZhdGlvbiUyMiUzQW51bGwlMkMlMjJhZ2dyZWdhdG9yJTIyJTNBbnVsbCUyQyUyMmZpbHRlciUyMiUzQSU3QiUyMmZpbHRlclR5cGUlMjIlM0ElMjJpbiUyMiUyQyUyMnZhbHVlcyUyMiUzQSU3QiUyMkIwMjc2NCUyMiUzQSU3QiUyMnZhbHVlJTIyJTNBJTIyQjAyNzY0JTIyJTJDJTIybGFiZWwlMjIlM0ElMjJCMDI3NjQlMjIlMkMlMjJsaXRlcmFsJTIyJTNBJTIyJ0IwMjc2NCclMjIlN0QlMkMlMjJCMDI3NjUlMjIlM0ElN0IlMjJ2YWx1ZSUyMiUzQSUyMkIwMjc2NSUyMiUyQyUyMmxhYmVsJTIyJTNBJTIyQjAyNzY1JTIyJTJDJTIybGl0ZXJhbCUyMiUzQSUyMidCMDI3NjUnJTIyJTdEJTJDJTIyQjAyODM1JTIyJTNBJTdCJTIydmFsdWUlMjIlM0ElMjJCMDI4MzUlMjIlMkMlMjJsYWJlbCUyMiUzQSUyMkIwMjgzNSUyMiUyQyUyMmxpdGVyYWwlMjIlM0ElMjInQjAyODM1JyUyMiU3RCU3RCUyQyUyMnRvVmFsdWVzJTIyJTNBJTdCJTdEJTJDJTIydG9nZ2xlU3RhdGUlMjIlM0ElMjJvcGVuJTIyJTdEJTdEJTVEJTJDJTIycm93cyUyMiUzQSU1QiU3QiUyMmNvbHVtbiUyMiUzQSUyMmh2ZmhzX2xpY2Vuc2VfbnVtJTIyJTJDJTIyY29sdW1uVHlwZSUyMiUzQSUyMlZBUkNIQVIlMjIlMkMlMjJkZXJpdmF0aW9uJTIyJTNBbnVsbCUyQyUyMmFnZ3JlZ2F0b3IlMjIlM0FudWxsJTJDJTIyaW5jbHVkZVRvdGFscyUyMiUzQXRydWUlN0QlMkMlN0IlMjJjb2x1bW4lMjIlM0ElMjJkaXNwYXRjaGluZ19iYXNlX251bSUyMiUyQyUyMmNvbHVtblR5cGUlMjIlM0ElMjJWQVJDSEFSJTIyJTJDJTIyZGVyaXZhdGlvbiUyMiUzQW51bGwlMkMlMjJhZ2dyZWdhdG9yJTIyJTNBbnVsbCU3RCU1RCU3RCU3RCU3RA==
